name: Update README with Latest Blog Posts
on:
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq libxml2-utils

      - name: Extract latest blog posts
        run: |
          RSS_FEED="http://jjrdd.tistory.com/rss"
          XML_DATA=$(curl -s $RSS_FEED)
          if [[ $? -ne 0 ]]; then
            echo "Failed to download RSS feed"
            exit 1
          fi

          POST_COUNT=5
          POSTS=$(echo "$XML_DATA" | xmllint --xpath '//item[position() <= '"$POST_COUNT"']' -)

          echo "## Latest Blog Posts" > latest-post.md
          for ((i=1; i<=$POST_COUNT; i++)); do
            TITLE=$(echo "$POSTS" | xmllint --xpath 'string((//item)['"$i"']/title)' - 2>/dev/null || echo "No title")
            LINK=$(echo "$POSTS" | xmllint --xpath 'string((//item)['"$i"']/link)' - 2>/dev/null || echo "No link")
            echo "[$TITLE]($LINK)" >> latest-post.md
          done

          cp README.md README_backup.md

          cat latest-post.md > README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'JoHyeonJi0408'
          git config --global user.email '1692074@hansung.ac.kr'
          git add README.md
          git commit -m "Update README with latest blog posts"
          git push
